# Generated by Django 4.2.5 on 2023-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('name',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonuser',
            options={'ordering': ('lesson', 'user'), 'verbose_name': 'Связь урока и пользователя', 'verbose_name_plural': 'Связи уроков и пользователей'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productuser',
            options={'ordering': ('product', 'user'), 'verbose_name': 'Связь продукта и пользователя', 'verbose_name_plural': 'Связи продуктов и пользователей'},
        ),
        migrations.AlterField(
            model_name='lessonuser',
            name='viewing_status',
            field=models.BooleanField(verbose_name='Статус просмотра'),
        ),
    ]
